export const INITIAL_DASHBOARD = 'INITIAL_STATE_TABLE/DASHBOARD';
export const SEARCH_DASHBOARD = 'SEARCH/DASHBOARD';
export const SORT_DASHBOARD = 'SORT_TABLE/DASHBOARD';
export const SORT_DASHBOARD_STATUS = 'SORT_TABLE_STATUS/DASHBOARD';

export const VALUE_SEARCH = ' VALUE_CHANGE_SEARCH/SEARCH_DASHBOARD';